// Generated by scripts/generate_routing.ts
export const SCENARIO_ROUTING: Record<string, { link?: string; articleId?: string; kbQuery?: string }> = {
  "syrian-lost-id": {
    "link": "/article/kimlik-lost-damaged",
    "articleId": "kimlik-lost-damaged",
    "kbQuery": "بدل ضائع كملك ضياع بطاقة الحماية المؤقتة kayip kimlik"
  },
  "syrian-prohibited-check": {
    "link": "/article/istanbul-closed-areas",
    "articleId": "istanbul-closed-areas",
    "kbQuery": "مناطق محظورة كملك سكن ايجار ممنوع نفوس مغلقة"
  },
  "syrian-travel-medical": {
    "link": "/article/travel-permit",
    "articleId": "travel-permit",
    "kbQuery": "إذن سفر طبي كملك Yol İzin Sağlık إحالة Sevk"
  },
  "syrian-travel-visit": {
    "link": "/article/travel-permit",
    "articleId": "travel-permit",
    "kbQuery": "إذن سفر زيارة Ziyaret كملك Yol İzin الولايات المحظورة"
  },
  "syrian-leaving-turkey": {
    "link": "/article/exit-cancel-residence-return-card"
  },
  "syrian-citizenship": {},
  "syrian-marriage": {
    "link": "/article/marriage-registration"
  },
  "syrian-newborn": {
    "link": "/article/family-birth-registration-flow"
  },
  "syrian-return-code": {
    "link": "/article/exit-cancel-residence-return-card"
  },
  "syrian-fix-address": {
    "link": "/article/address-registration-problems"
  },
  "syrian-denklik": {
    "link": "/article/highschool-denklik"
  },
  "tourist-new": {
    "link": "/article/tourist-residence"
  },
  "tourist-extension": {
    "link": "/article/real-estate-residence"
  },
  "tourist-reject": {
    "link": "/article/tourist-residence"
  },
  "tourist-overstay": {
    "link": "/article/exit-cancel-residence-return-card"
  },
  "tourist-convert-kimlik": {
    "link": "/article/kimlik-to-residence",
    "articleId": "kimlik-to-residence",
    "kbQuery": "تحويل الكملك إلى إقامة ختم دخول قبل 2016 e-ikamet"
  },
  "tourist-bank-open": {
    "link": "/article/bank-account-documents"
  },
  "investor-citizen": {
    "link": "/article/real-estate-citizenship"
  },
  "investor-residence": {
    "link": "/article/real-estate-residence"
  },
  "company-setup": {
    "link": "/article/company-setup"
  },
  "company-monthly-obligations": {
    "kbQuery": "التزامات شركة شهرية تركيا محاسب ضرائب SGK دفاتر فواتير إلكترونية"
  },
  "company-closure": {
    "kbQuery": "إغلاق شركة تركيا تصفية LTD سجل تجاري ضرائب محاسب"
  },
  "bank-block": {
    "link": "/article/bank-account-documents"
  },
  "phone-imei": {
    "link": "/article/phone-imei-register"
  },
  "consumer-complaint": {
    "link": "/article/consumer-rights-complaint"
  },
  "debt-check": {
    "link": "/article/gss-debt-inquiry"
  },
  "student-residence": {
    "link": "/article/student-residence"
  },
  "student-denklik": {
    "link": "/article/highschool-denklik"
  },
  "student-yos": {
    "link": "/article/yos-exam-guide"
  },
  "work-permit-employee": {
    "link": "/article/work-permit-residence"
  },
  "work-permit-company": {},
  "work-permit-cost": {},
  "housing-rent-increase": {
    "link": "/article/renting-house"
  },
  "housing-deposit": {
    "link": "/article/deposit-return"
  },
  "housing-eviction": {},
  "housing-tahliye-undertaking": {},
  "housing-rent-payment-legal": {},
  "housing-aidat": {},
  "housing-depozito-limit": {},
  "housing-kombi-responsibility": {},
  "housing-airbnb-law": {},
  "travel-cash-limit": {},
  "travel-exit-tax": {},
  "travel-pets": {},
  "travel-gold": {},
  "daily-fast": {},
  "daily-paypal": {},
  "daily-crypto": {},
  "daily-credit-score": {},
  "daily-booking-block": {},
  "syrian-syria-visit-risk": {
    "link": "/article/exit-cancel-residence-return-card"
  },
  "syrian-marriage-not-registered": {},
  "syrian-bank-kimlik-yellow": {},
  "syrian-child-school-no-kimlik": {},
  "syrian-property-ownership": {
    "link": "/article/real-estate-citizenship"
  },
  "student-tomer": {},
  "student-open-highschool": {},
  "student-mavi-diploma": {},
  "worker-bagkur": {},
  "worker-meal-card": {},
  "worker-uber-illegal": {},
  "car-foreign-vehicle-duration": {},
  "car-drive-with-foreign-license": {},
  "car-hgs-payment": {},
  "car-mtv": {},
  "legal-deport": {},
  "legal-divorce": {},
  "daily-edevlet": {},
  "daily-uets": {},
  "daily-cimer": {},
  "daily-enabiz": {},
  "daily-family-doctor": {},
  "daily-family-doctor-change": {},
  "daily-uyap": {},
  "daily-kades": {},
  "daily-address": {},
  "daily-notary": {},
  "student-transcript": {
    "link": "/article/transcript-edevlet"
  },
  "student-highschool-denklik": {
    "link": "/article/highschool-denklik"
  },
  "daily-goc-appointment": {
    "link": "/article/kimlik-data-update"
  },
  "daily-nvi-appointment": {
    "link": "/article/driving-license"
  },
  "daily-lost-driving-license": {
    "link": "/article/lost-driving-license"
  },
  "daily-mobile-lines-check": {
    "link": "/article/mobile-lines-check"
  },
  "daily-mhrs-booking": {
    "link": "/article/hospital-appointment"
  },
  "daily-bank-open": {},
  "daily-citizenship-status": {
    "link": "/article/citizenship-status-check"
  },
  "protection-status-2026": {
    "kbQuery": "الحماية المؤقتة 2026 إنهاء كملك إقامة تأمين صحي تحويل"
  },
  "syria-visit-official": {
    "kbQuery": "زيارة سوريا كملك معبر رسمي باب الهوى جرابلس إذن"
  },
  "syria-mass-return-2025": {
    "kbQuery": "العودة الجماعية سوريا 2024 2025 طوعية ترحيل UNHCR حقوق"
  }
};
