
import { CONSULTANT_SCENARIOS } from '../src/lib/consultant-scenarios';
import fs from 'fs';
import path from 'path';

const routing = Object.fromEntries(
    Object.entries(CONSULTANT_SCENARIOS).map(([key, value]) => [
        key,
        {
            link: value.link,
            articleId: value.articleId,
            kbQuery: value.kbQuery,
            // Keep title/desc for initial placeholder or SEO? No, fetch dynamic.
        }
    ])
);

const content = `// Generated by scripts/generate_routing.ts
export const SCENARIO_ROUTING: Record<string, { link?: string; articleId?: string; kbQuery?: string }> = ${JSON.stringify(routing, null, 2)};
`;

fs.writeFileSync(path.join(process.cwd(), 'src/lib/consultant-routing.ts'), content);
console.log('Generated src/lib/consultant-routing.ts');
