-- إصلاح مقتطفات البحث — 126 مقالاً
-- ===========================================================================
-- المشكلة المقيسة: من 348 مقالاً منشوراً، 129 مقتطفه مكسور:
--   73 عنوان seo أطول من 60 حرفاً  → غوغل يقطع الرسالة في منتصفها
--   67 وصفاً أطول من 160 حرفاً      → الجملة التي تكسب النقرة تُقطع
--   46 وصفاً أقصر من 70 حرفاً       → الخانة مهدورة
-- والموقع في المرتبة 6.2 وسطياً بنسبة نقر 4.5% — أي أن غوغل يعرض الصفحات
-- ولا أحد يضغط. المقتطف هو الرافعة.
--
-- كل وصف أُعيدت كتابته من نصّ مقاله نفسه: العنوان والمقدمة وأول المتن. ثم
-- فحصتُ آلياً كل رقم في الأوصاف الـ126 — سعراً كان أو مهلةً أو نسبةً أو رقم
-- مادة — ومطابقتُه على نصّ مقاله. النتيجة: صفر رقم غير موجود في مصدره.
-- وصفر تجاوز للأطوال، وصفر تكرار في العناوين أو الأوصاف.
--
-- وثلاثة مقالات رُفضت عمداً ولم تُدرَج، لأن صفحاتها لا تجيب عناوينها أصلاً:
--   finance-luxury-property-tax — لا عتبة ولا نسبة ولا سنة في المتن
--   travel-muzekart            — العنوان يعد بفرق أسعار، والمتن لا يذكر سعراً
--   frozen-id-problem          — العنوان يعد بالحل، والمتن يذكر السبب فقط
-- تزيينُ مقتطفٍ لصفحة لا تجيب يجعل النقرة ضائعة ويضرّ السمعة. هذه الثلاثة
-- تحتاج محتوى لا عنواناً.
--
-- العناوين الظاهرة للقرّاء (title) لم تُمسّ — التعديل على حقلَي المقتطف فقط.
-- ملاحظة على الطول: الموقع نفسه يقصّ الوصف عند 155 حرفاً ويضيف «…»
-- (src/app/article/[id]/page.tsx:434). فكل وصف هنا 155 حرفاً أو أقلّ حتى لا
-- تُقطع جملته الأخيرة. سبعة عشر وصفاً قُصّرت لهذا السبب بعد التشغيل الأول.
--
-- شغّله في Supabase → SQL Editor. الملف idempotent.
UPDATE articles SET seo_title = 'شرط 185 يوماً لإدخال السيارة بلوحة أجنبية: استعلام e-Devlet', seo_description = 'الشرط: إقامة 185 يوماً خارج تركيا خلال السنة السابقة لإدخال سيارة بلوحة أجنبية ثلاثة أشهر. كيف تتحقّق عبر e-Devlet، ومن يحقّ له قيادتها بعد الدخول' WHERE slug = '185-days-foreign-plated-car-turkey-2026';
UPDATE articles SET seo_title = 'بعد اليوس 2026: الترشيح والقبول والتسجيل في جامعات تركيا', seo_description = 'درجة اليوس وحدها لا تحجز مقعداً؛ تتقدّم لكل جامعة على حدة. كيف تقرأ الكوتا والحد الأدنى للنقاط في YÖKATLAS، وتوزّع ترشيحاتك حتى القبول والتسجيل النهائي.' WHERE slug = 'after-yos-turkey-university-tercih-application-registration-2026';
UPDATE articles SET seo_title = 'تصديق الوكالات في القنصلية السورية', seo_description = 'الوكالة هي المستند الأهم لإدارة الأملاك أو الأحوال الشخصية في سوريا من الخارج. كيف تنظّم وكالة خاصة أو عامة وتصدّقها لدى القنصلية السورية.' WHERE slug = 'agency-attestation-legacy';
UPDATE articles SET seo_title = 'معبر Akçakale يفتح بجواز السفر من 12 مايو 2026', seo_description = 'من 12 مايو 2026 يستقبل معبر Akçakale الدخول والخروج بجواز السفر: أتراك، مزدوجو الجنسية، وسوريون بإقامة أو إذن عمل ساري. أصحاب الحماية المؤقتة غير مشمولين.' WHERE slug = 'akcakale-border-passport-syrians-2026';
UPDATE articles SET seo_title = 'الحد الأدنى للأجور في تركيا 2026: الصافي والإجمالي', seo_description = 'الحد الأدنى للأجور في تركيا 2026: 28,075.50 ليرة صافياً و33,030 إجمالاً، وأجر يومي 1,101 ليرة، مع الاقتطاعات 4,954.50 ليرة وتكلفة العامل على صاحبه' WHERE slug = 'asgari-ucret-turkiye-2026-net-brut-isveren-maliyeti';
UPDATE articles SET seo_title = 'فحص الخبرة (Ekspertiz) قبل شراء سيارة مستعملة', seo_description = 'الـEkspertiz فحص فني مدفوع في مراكز مختصة يكشف حالة المحرك والهيكل والدهان والحوادث السابقة، فتعرف العيوب قبل الدفع وتتفق على سعر عادل.' WHERE slug = 'auto-ekspertiz-guide';
UPDATE articles SET seo_title = 'HGS/OGS: شراء الشارة من PTT أو البنك ودفع المخالفات', seo_description = 'HGS نظام عبور الطرق السريعة والجسور، والعبور بدون رصيد كاف يولد مخالفات. فعّل الشارة واربطها بوسيلة دفع أو عبئها دورياً، وراجع الاستعلام باستمرار.' WHERE slug = 'auto-hgs-ogs';
UPDATE articles SET seo_title = 'التأمين الإلزامي Trafik أم الشامل Kasko: أيهما تختار؟', seo_description = 'Trafik يغطي مسؤوليتك تجاه الطرف الآخر ضمن حدود، وKasko اختياري يوسع التغطية لسيارتك حسب البوليصة. القرار يعتمد على قيمة السيارة وطريقة استخدامك.' WHERE slug = 'auto-insurance-trafik-vs-kasko';
UPDATE articles SET seo_title = 'ضريبة المركبات MTV: مواعيد الدفع والاستعلام', seo_description = 'ضريبة المركبات MTV تُدفع غالباً على دفعتين في يناير ويوليو. كيف تستعلم عن المبلغ وتدفعه عبر القنوات الرسمية أو البنوك في موعده لتقليل الغرامات.' WHERE slug = 'auto-mtv-payment';
UPDATE articles SET seo_title = 'الفحص الدوري TÜVTÜRK: الحجز والوثائق وإعادة الفحص', seo_description = 'الفحص الدوري شرط قانوني للمركبة: تحجز موعداً، تجهز وثائق السيارة، وتراجع المركز. وإن سجلت ملاحظات تصلحها ثم تعيد الفحص ضمن مدة محددة.' WHERE slug = 'auto-tuvturk-inspection';
UPDATE articles SET seo_title = 'إذن العمل المستقل في تركيا 2026: رسم 125,802.20 ل.ت والشروط', seo_description = 'رسمه السنوي 125,802.20 ل.ت زائد 964 ل.ت للبطاقة، وتدفع ضمانك بنفسك (Bağ-Kur 4B). من يحتاجه، شروط الأهلية وخطة العمل، ووضع السوريين تحت الكملك.' WHERE slug = 'bagimsiz-calisma-izni-2026';
UPDATE articles SET seo_title = 'فتح حساب بنكي للسوريين بالكملك 2026', seo_description = 'فتح الحساب بات أصعب في بعض البنوك لكنه متاح قانونياً بالكملك. البنوك المفضلة: Ziraat Bankası وVakıf Katılım وKuveyt Türk، والشروط المطلوبة.' WHERE slug = 'bank-account-opening';
UPDATE articles SET seo_title = 'شراء عقار في تركيا 2026: دليل الأجانب والوضع الخاص للسوريين', seo_description = 'الوثائق وخطوات الطابو، وجدول الرسوم والضرائب 2026، ومسارا الجنسية والإقامة عبر العقار، ولماذا يُمنع السوري قانوناً من تسجيل عقار باسمه الشخصي.' WHERE slug = 'buying-property-turkey-2026';
UPDATE articles SET seo_title = 'إعفاء إذن العمل أم إذن عمل كامل؟ وأرقام وزير الداخلية', seo_description = 'وزير الداخلية أعلن إعفاء المشمولين بالحماية المؤقتة من إلزامية إذن العمل، وأرقاماً: 2,264,983 سورياً و3,632,064 أجنبياً بإقامة. ما يمنحه وما لا يمنحه' WHERE slug = 'ciftci-syrians-decisions-work-permit-exemption-2026-06';
UPDATE articles SET seo_title = 'تتبع طلب الجنسية التركية: الرابطان الرسميان وحالات الملف', seo_description = 'استعلم عن حالة ملف التجنيس عبر e-Devlet أو موقع مديرية النفوس مباشرة، مع تحذير من رابط متداول لا وجود له، وشرح معنى كل حالة ولماذا قد لا يظهر ملفك أصلاً.' WHERE slug = 'citizenship-status-check';
UPDATE articles SET seo_title = 'دليل أضنة 2026 للسوريين والعرب: الأحياء والخدمات', seo_description = 'دليل القادم الجديد إلى أضنة: مناطقها الـ15 ومركزها سيحان ويوريغير وتشوكوروفا وصاريتشام، والأحياء المفتوحة والمغلقة لتسجيل الأجانب، وأين تنجز معاملاتك' WHERE slug = 'city-guide-adana-2026';
UPDATE articles SET seo_title = 'دليل هاتاي (أنطاكية) 2026 للسوريين: الأحياء والخدمات', seo_description = 'ما يحتاجه القادم إلى هاتاي: أقضيتها الـ15 من أنطاكية إلى الإسكندرونة وريحانلي، كيف تعرف الأحياء المفتوحة والمغلقة لتسجيل الأجانب، وأين تنجز معاملات النفوس.' WHERE slug = 'city-guide-hatay-2026';
UPDATE articles SET seo_title = 'دليل السوريين والعرب في مرسين 2026: الأحياء والخدمات', seo_description = 'أقضية مرسين الـ13 من أكدنيز ومزيتلي إلى طرسوس وسيليفكة، وأين تتركّز الجالية السورية، وكيف تتحقق بأداة حيّة من الأحياء المفتوحة والمغلقة للأجانب' WHERE slug = 'city-guide-mersin-2026';
UPDATE articles SET seo_title = 'تسجيل الزواج المدني في تركيا 2026 — الأوراق ودفتر العائلة', seo_description = 'يُسجَّل الزواج في دائرة الزواج بالبلدية (Evlendirme Dairesi): شهادة عزوبية مترجمة ومصدّقة لدى النوتر، فحص طبي للطرفين، ثم دفتر العائلة (Aile Cüzdanı).' WHERE slug = 'civil-marriage-registration-turkey';
UPDATE articles SET seo_title = 'تخفيض 80٪ من الأحياء المغلقة أمام الأجانب في تركيا 2026', seo_description = 'إعلان UCSO في 6 يونيو 2026: شطب نحو 80٪ من قائمة 2022 التي ضمّت 1,169 حياً مغلقاً أمام عناوين الأجانب. بدأ التطبيق في أورفا وكلس، والقاعدة لم تُلغَ كلّياً.' WHERE slug = 'closed-neighborhoods-80-percent-reduction-2026';
UPDATE articles SET seo_title = 'حق الإرجاع خلال 14 يوماً في الشراء أونلاين: متى ينطبق؟', seo_description = 'في الشراء عن بُعد حق إرجاع ضمن مدة محددة تُذكر كثيراً بـ14 يوماً، مع استثناءات حسب نوع المنتج؛ وشرح عملي لحفظ سجل الطلب والمراسلات وطلب الإرجاع بوقته.' WHERE slug = 'consumer-14-day-return';
UPDATE articles SET seo_title = 'الاحتيال الشائع على الأجانب في تركيا: كيف تحمي نفسك', seo_description = 'أشكال الاحتيال الأكثر شيوعاً: عروض عقارية مغرية جداً، روابط دفع مزيفة، انتحال صفة جهة رسمية، وطلب تحويل فوري. القاعدة: لا تدفع بلا وثائق ومسار رسمي.' WHERE slug = 'consumer-common-frauds';
UPDATE articles SET seo_title = 'شكوى حماية المستهلك (Tüketici Hakem Heyeti)', seo_description = 'اشتريت منتجاً معيباً ورفض البائع إرجاعه؟ هيئة التحكيم للمستهلك جهة حكومية تحل الخلاف مجاناً، وقرارها ملزم للبائع تحت حد معين من قيمة المنتج.' WHERE slug = 'consumer-rights-complaint';
UPDATE articles SET seo_title = 'التوقيع الإلكتروني (e-İmza): ما هو ومن أين تشتريه؟', seo_description = 'التوقيع الإلكتروني (e-İmza) وسيلة توقيع رقمية معتمدة لمعاملات تتطلب تحققاً أعلى، يُشترى من مزودين معتمدين بإجراءات تعريف، ومتى تحتاجه فعلاً حسب عملك.' WHERE slug = 'digital-e-imza';
UPDATE articles SET seo_title = 'KEP (البريد الإلكتروني المسجل): ما هو وكيف تفتحه', seo_description = 'KEP بريد إلكتروني مسجل يُستخدم في التبليغات الرسمية والمراسلات القانونية ويمنح إثبات إرسال واستلام معتمداً. يُفتح لدى مزودين معتمدين بعد تحقق الهوية.' WHERE slug = 'digital-kep';
UPDATE articles SET seo_title = 'عقود الإيجار الرقمية عبر e-Devlet بدل توثيق النوتر', seo_description = 'منذ نهاية 2024 يمكن توثيق عقد الإيجار إلكترونياً عبر e-Devlet دون الحاجة إلى توثيق النوتر، والعقد الصادر عبر النظام معتمد لتثبيت النفوس.' WHERE slug = 'digital-lease-contract';
UPDATE articles SET seo_title = 'تحديث خط الهاتف بعد الجنسية أو تغيير رقم الهوية', seo_description = 'عند تغيّر نوع وثيقتك أو رقم هويتك قد تفقد الوصول إلى رسائل الـOTP والبنوك؛ تحديث بيانات الخط يتم في فرع الشركة بوثائق إثبات، وقد يشمل نقل ملكية الخط.' WHERE slug = 'digital-line-transfer-citizenship';
UPDATE articles SET seo_title = 'معادلة الشهادة الجامعية (Denklik) للسوريين 2026: 1,250 ل.ت', seo_description = 'رسم المعادلة الرسمي 1,250 ل.ت والتكلفة الإجمالية مع الترجمة 8,000-15,000 ل.ت، وسوريا ضمن دول الحرب فتُقبل بدائل للوثائق المفقودة. الخطوات والوثائق.' WHERE slug = 'diploma-denklik-syrians-arabs-2026';
UPDATE articles SET seo_title = 'تصديق الشهادات من تركيا إلى سوريا 2026: الثانوية والجامعية', seo_description = 'تصديق الشهادة الثانوية حسب نوع الدراسة (تعليم مفتوح، مدارس سورية مؤقتة، نظامية، مهنية) ثم الوثائق الجامعية: التربية، الأبوستيل، الخارجية التركية، القنصلية.' WHERE slug = 'document-attestation-turkey-to-syria-students-2026';
UPDATE articles SET seo_title = 'رسوم رخصة القيادة في تركيا 2026: كل الفئات والتكلفة الكاملة', seo_description = 'الرسوم الرسمية 2026: رخصة الفئة B بـ8,869.60 ل.ت، والدراجات A/A1/A2/F بـ4,354.90، والشاحنات والحافلات بـ13,386.20، مع امتحاني MEB 950 و2,000 ل.ت.' WHERE slug = 'driving-license-fees-2026';
UPDATE articles SET seo_title = 'e-Nabız 2026: سجلك الصحي الإلكتروني في تركيا للأجانب', seo_description = 'تحاليلك وصور الأشعة والوصفات واللقاحات كلها محفوظة في e-Nabız مجاناً. كيف تنشئ حسابك عبر e-Devlet أو enabiz.gov.tr، وكيف تشارك سجلك مع طبيبك الجديد.' WHERE slug = 'e-nabiz-electronic-health-record-2026';
UPDATE articles SET seo_title = 'ما هو تطبيق e-Nabız وماذا يحفظ من سجلاتك الطبية؟', seo_description = 'e-Nabız منصة حكومية تركية تحفظ سجلاتك الطبية ونتائج التحاليل والصور الشعاعية، وتتيح متابعة المواعيد واللقاحات بالارتباط مع الأنظمة الصحية الحكومية.' WHERE slug = 'e-nabiz-guide';
UPDATE articles SET seo_title = 'استخراج ورقة أعزب / أهلية زواج عبر e-Devlet', seo_description = 'كيف تقدّم طلب أهلية الزواج (ورقة أعزب) عبر e-Devlet: إدخال بيانات التواصل واختيار البلدية وتعبئة بيانات الطرف الآخر وإرفاق الوثائق، ثم متابعة الطلب.' WHERE slug = 'edevlet-evlenme-ehliyet';
UPDATE articles SET seo_title = 'استخراج إذن السفر (Yol İzin) للاجئين إلكترونياً', seo_description = 'إذن السفر تصريح رسمي للتنقل بين الولايات. الطلب يُقدَّم إلكترونياً وتحدد فيه سبب السفر والولاية وتاريخي الذهاب والعودة، مع مرفقات تثبت السبب.' WHERE slug = 'edevlet-yol-izin';
UPDATE articles SET seo_title = 'التعليم الجامعي والمنح للسوريين (TR-YÖS 2026)', seo_description = 'امتحان TR-YÖS بات إلزامياً في معظم الجامعات الحكومية، وأُلغي الإعفاء من الرسوم الجامعية لمعظم السوريين عدا فئات محددة. شروط القبول والمنح.' WHERE slug = 'education-universities';
UPDATE articles SET seo_title = 'العمل الحر (Freelance) في تركيا: الضرائب والإيصالات', seo_description = 'ما يلزم للعمل كمستقل بشكل نظامي: تسجيل ضريبي وإصدار إيصالات (Serbest Meslek Makbuzu) وغالباً محاسب، وكيف تختلف المتطلبات حسب نشاطك ووضع إقامتك.' WHERE slug = 'employment-freelance-legal';
UPDATE articles SET seo_title = 'إذن العمل: الفرق بين الحماية المؤقتة والإقامة السياحية', seo_description = 'صاحب العمل هو من يقدّم طلب إذن العمل، لكن الجهة والمستندات ومتطلبات التأمين تختلف بين كملك الحماية المؤقتة والإقامة السياحية، وهذه أسئلتك له.' WHERE slug = 'employment-work-permit-kimlik-vs-tourist';
UPDATE articles SET seo_title = 'حقوق العامل: تعويض نهاية الخدمة (Kıdem) وخط ALO 170', seo_description = 'ما توثّقه من أوراقك قبل أي خلاف: الأجر وساعات العمل والتأمين، وشروط تعويض نهاية الخدمة (Kıdem)، ومتى تتصل بخط الشكاوى ALO 170 عند فصل تعسفي.' WHERE slug = 'employment-worker-rights-kidem-alo170';
UPDATE articles SET seo_title = 'تسجيل طفلك في المدرسة الحكومية التركية: العمر ونظام e-Okul', seo_description = 'التعليم الحكومي مجاني لأطفال الحماية المؤقتة: يُسجَّل الطالب في أقرب مدرسة لعنوانه عبر e-Okul، والصف الأول من عمر 69 شهراً (66–68 بطلب من الولي).' WHERE slug = 'enroll-child-turkish-public-school';
UPDATE articles SET seo_title = 'إعفاء إذن العمل للسوريين: خطوات التفعيل والتنبيهات', seo_description = 'الإعفاء آلية قائمة منذ تعديل أكتوبر 2024 لا قرار جديد: التقديم عبر emuafiyet.csgb.gov.tr، تفعيل السيغورتا (SGK)، المهن المحظورة، وعلاقة الإعفاء بإذن السفر.' WHERE slug = 'exemption-work-permit-full-guide-2026-06';
UPDATE articles SET seo_title = 'إسقاط الإقامة وتسليم الكرت في المطار: متى وكيف؟', seo_description = 'متى قد يُطلب تسليم بطاقة الإقامة عند المغادرة، ولماذا يختلف التطبيق حسب نوع الإقامة ووضعك القانوني، وكيف تغادر بسجل نظيف بلا ديون أو التزامات مفتوحة.' WHERE slug = 'exit-cancel-residence-return-card';
UPDATE articles SET seo_title = 'إغلاق الحسابات البنكية قبل المغادرة لتجنب الرسوم', seo_description = 'ترك الحساب مفتوحاً بعد المغادرة يعني رسوم إدارة واشتراكات مستمرة. صفِّ البطاقات والقروض وأوامر الدفع التلقائي، ثم أغلق الحساب رسمياً بورقة تثبت ذلك.' WHERE slug = 'exit-close-bank-accounts';
UPDATE articles SET seo_title = 'بيع الأثاث المستعمل عبر Spotçu بسعر عادل', seo_description = 'بيع أثاثك قبل المغادرة يتم عبر تجار المستعمل (Spotçu) أو منصات الإعلانات. وثّق حالة القطع، حدّد سعراً منطقياً، ولا تسلّم شيئاً قبل اتفاق واضح.' WHERE slug = 'exit-sell-used-furniture-spotcu';
UPDATE articles SET seo_title = 'استرداد تأمين العداد (Güvence Bedeli) عند إنهاء الاشتراك', seo_description = 'عند إنهاء اشتراك الكهرباء أو الماء أو الغاز أو نقل العداد قد يحق لك استرداد مبلغ التأمين بعد تسوية الفواتير، عبر الشركة أو المكتب المختص في مدينتك.' WHERE slug = 'exit-utility-deposit-refund';
UPDATE articles SET seo_title = 'تسجيل المولود في تركيا: من المستشفى إلى النفوس والإقامة', seo_description = 'ترتيب أوراق المولود الجديد: تقرير الولادة من المستشفى (Doğum Raporu)، ثم التسجيل في النفوس، ثم وثائق القنصلية حسب الجنسية، ثم ترتيب إقامة الطفل.' WHERE slug = 'family-birth-registration-flow';
UPDATE articles SET seo_title = 'شحن الجثمان للخارج (Cenaze Nakil): الخطوات العامة', seo_description = 'نقل الجثمان إلى بلد آخر يحتاج تنسيقاً بين الجهات الطبية والبلدية والمطار وشركات النقل، وقد تدخل القنصلية. المستندات وتفاصيل النقل تختلف حسب الوجهة.' WHERE slug = 'family-cenaze-nakil';
UPDATE articles SET seo_title = 'الوفاة في تركيا: إجراءات الدفن والوثائق المطلوبة', seo_description = 'عند الوفاة داخل تركيا: إثبات الوفاة، استخراج الوثائق اللازمة، ثم الدفن عبر مديرية المقابر البلدية. وللأجانب خطوات إضافية مع القنصلية وترجمة الوثائق.' WHERE slug = 'family-death-procedures';
UPDATE articles SET seo_title = 'حصر الإرث (Veraset İlamı) للأجانب: ما هو وكيف تبدأ؟', seo_description = 'حصر الإرث وثيقة تحدد الورثة ونِسبهم، وهي أول خطوة لتقسيم إرث بنكي أو عقاري في تركيا؛ وللأجانب وثائق من بلد المتوفى وترجمة وتصديق وغالباً محامٍ.' WHERE slug = 'family-inheritance-veraset-ilami';
UPDATE articles SET seo_title = 'توقّف دعوة الأقارب عبر لبنان: مسار الأردن وحده متاح', seo_description = 'توقّف مسار لبنان حتّى إشعار آخر، وبقي الأردن وحده: يبقى المدعوّ في الأردن من 20 يوماً إلى شهر حتّى صدور القرار. يخصّ مزدوجي الجنسية وأصحاب الإقامات' WHERE slug = 'family-invitation-jordan-only-2026';
UPDATE articles SET seo_title = 'تجديد الإقامة العائلية في تركيا 2026: المهلة والخطوات', seo_description = 'قدّم التمديد خلال آخر 60 يوماً وقبل تاريخ الانتهاء: خطوات e-ikamet، رمزا الدفع 9207 و9233، مهلة البتّ 90 يوماً، والسفر مسموح 15 يوماً فقط أثناء المعاملة.' WHERE slug = 'family-residence';
UPDATE articles SET seo_title = 'السجل الائتماني Findeks: كيف تبني نقاطك لبطاقة أو قرض', seo_description = 'نقاط Findeks تتأثر بسلوك الدفع: فواتير منتظمة، استخدام معتدل للبطاقة، وتجنب التأخير. وقبول الأجانب يختلف بين البنوك حسب الوضع القانوني والدخل.' WHERE slug = 'finance-findeks-credit-score';
UPDATE articles SET seo_title = 'الوديعة المحمية (KKM): هل ما زالت متاحة وكيف تسأل البنك؟', seo_description = 'توفّر الوديعة المحمية (KKM) وشروطها يتغيران بقرارات رسمية وسياسات البنوك؛ اسأل البنك عن الأهلية والعملة ومدة الربط وحساب العائد والإنهاء المبكر.' WHERE slug = 'finance-kkm-status';
UPDATE articles SET seo_title = 'Tax Free واسترداد ضريبة KDV لغير المقيمين: الشروط', seo_description = 'استرداد KDV يشترط عادة أن تكون غير مقيم وأن تخرج من البلد بفاتورة Tax Free مختومة. الشروط تتغير، والمرجع تعليمات المتجر والجمارك في المطار.' WHERE slug = 'finance-taxfree-vat-refund';
UPDATE articles SET seo_title = 'الحد الأدنى لراتب الأجنبي في تركيا 2026 حسب المهنة', seo_description = 'إذن العمل يُرفض إذا قلّ الراتب عن حدّ المهنة: 165,150 ل.ت للمدير التنفيذي، 132,120 للمهندس، 99,090 للطبيب والمعلم، 66,060 للمبرمج، 33,030 للمهن العادية.' WHERE slug = 'foreigner-minimum-salary-2026';
UPDATE articles SET seo_title = 'غازي عنتاب: شروط التقديم على الجنسية التركية بعد 5 سنوات', seo_description = 'مديرية النفوس في غازي عنتاب أعلنت شروط التقديم العام على الجنسية: 5 سنوات إقامة قانونية، غياب خارج تركيا لا يتجاوز 360 يوماً، وأوراق مصدّقة بالأبوستيل.' WHERE slug = 'gaziantep-citizenship-decision-syrians-2026';
UPDATE articles SET seo_title = 'القنصلية السورية في غازي عنتاب 2026: الخدمات والمواعيد', seo_description = 'افتُتحت في حزيران 2026 لتخدم سوريي الجنوب من كلس إلى أضنة: خدمات الجوازات والتوكيلات وحجز الموعد رسمياً، مع تنبيه أن الرسوم والأوراق تتغيّر.' WHERE slug = 'gaziantep-syrian-consulate-opens-2026-06-11';
UPDATE articles SET seo_title = 'إدارة الهجرة تنفي ارتفاع رسوم الإقامة — بيان 30 أبريل 2026', seo_description = 'بيان إدارة الهجرة في 30 أبريل 2026 ينفي رفع رسوم الإقامة: الأرقام السارية منذ يناير هي 964 ل.ت للبطاقة و3,359.90 للشهر الأول، والسوريون يدفعون البطاقة فقط.' WHERE slug = 'goc-idaresi-fees-no-change-april-2026';
UPDATE articles SET seo_title = 'إدارة الهجرة: 2,255,317 سورياً و1,044,123 عائداً طوعاً', seo_description = 'بيان إدارة الهجرة التركية: 2,255,317 سورياً تحت الحماية المؤقتة، و1,044,123 عادوا طوعاً منذ 2016، منهم 700,120 منذ 8 ديسمبر 2024، ولماذا رقمان' WHERE slug = 'goc-idaresi-syrians-return-figures-2026-06';
UPDATE articles SET seo_title = 'مركز تحديثات إدارة الهجرة التركية 2026 — 7 تحديثات منفصلة', seo_description = 'سبعة تحديثات من إدارة الهجرة التركية 2026، كلّ واحد في مقال مستقلّ: أحياء أورفا وقونيا المغلقة، إذن كلس التجاري، دعوة الأقارب عبر الأردن، ومعبر Akçakale.' WHERE slug = 'goc-idaresi-updates-2026';
UPDATE articles SET seo_title = 'قسط GSS 2026: 1,981 ل.ت للمواطنين و7,927 للأجانب', seo_description = 'قسط التأمين الصحي العام GSS في 2026: 1,981.80 ل.ت شهرياً للمواطنين و7,927.20 للأجانب وحاملي البطاقة الزرقاء، والسوريون تحت الحماية المؤقتة مستثنون.' WHERE slug = 'gss-premium-2026-foreigners-syrians';
UPDATE articles SET seo_title = 'اشتراكات المنزل في تركيا 2026: كهرباء وماء وغاز وإنترنت', seo_description = 'أوراق فتح اشتراكات الكهرباء والماء والغاز والإنترنت في تركيا 2026: رقم العداد وعقد الإيجار وشرط DASK للكهرباء والماء، وبدل الضمان الذي يُسترد عند المغادرة.' WHERE slug = 'home-subscriptions-turkey-2026';
UPDATE articles SET seo_title = 'العائدات (Aidat) في المجمعات: كيف تعترض على زيادة؟', seo_description = 'العائدات (Aidat) تُحدد وفق ميزانية المجمع وخدماته؛ الاعتراض يبدأ بطلب تفاصيل مكتوبة للميزانية والخدمات، ثم توثيق اعتراضك داخلياً أو قانونياً.' WHERE slug = 'housing-advanced-aidat-dispute';
UPDATE articles SET seo_title = 'تأمين الزلازل DASK: إلزاميته وتغطيته وطلب التعويض', seo_description = 'DASK مطلوب عادة لفتح عدادات الخدمات أو نقلها، ويغطي أضراراً محددة من الزلازل ضمن حدود البوليصة. عند الضرر تحتاج بلاغاً ووثائق وصوراً وتقييماً من الشركة.' WHERE slug = 'housing-advanced-dask';
UPDATE articles SET seo_title = 'حقوق الجوار والضوضاء: تصرف قانوني بدون تصعيد', seo_description = 'التعامل مع ضوضاء الجيران يبدأ بالتفاهم، ثم إدارة المجمع، ثم توثيق الحالة، ثم البلاغ عند الضرورة. الأدلة تحميك، والتصعيد المتهور قد ينعكس عليك.' WHERE slug = 'housing-advanced-neighbor-noise';
UPDATE articles SET seo_title = 'Apostille أم تصديق قائمقام أم والي؟ الفرق العملي', seo_description = 'الأبوستيل تصديق دولي وفق اتفاقية لاهاي لوثيقة ستُستعمل خارج تركيا، أما داخلها فالتصديق عبر القائمقام أو الوالي حسب نوع الوثيقة والجهة المُصدِرة.' WHERE slug = 'identity-apostille-kaymakam-valilik';
UPDATE articles SET seo_title = 'التسجيل في İŞKUR 2026: وظائف ودورات مجانية للسوريين', seo_description = 'بعد ستة أشهر تحت الحماية المؤقتة تفتح سجل باحث عن عمل في İŞKUR عبر e-Şube أو e-Devlet، فتصل إلى إعلانات الوظائف الرسمية ودورات مهنية بشهادة ومصروف يومي.' WHERE slug = 'iskur-is-arayan-kaydi-mesleki-kurslar-2026-suriyeliler';
UPDATE articles SET seo_title = 'تحديث بيانات الكملك والعنوان 2026: مهلة 20 يوم عمل', seo_description = 'تبليغ تغيير العنوان واجب خلال عشرين يوم عمل بنص القانون 5490 وإلا غرامة إدارية. متى يلزم التحديث، خطوات حجز الموعد، وأخطاء وثيقة العنوان التي تؤخّر الملف.' WHERE slug = 'kimlik-data-update';
UPDATE articles SET seo_title = 'رسوم الأدوية لحاملي الكملك 2026: كم تدفع في الصيدلية', seo_description = 'منذ 1 كانون الثاني 2026 تُحصّل الصيدلية حصة مشاركة من حاملي الكملك: 20% من ثمن الدواء (10% لأصحاب الدخل والتقاعد) وبدل وصفة 3,76 ليرة حتى ثلاث علب دواء.' WHERE slug = 'kimlik-ilac-recete-katilim-payi-sgk-teb-2026';
UPDATE articles SET seo_title = 'ما هو الكملك؟ الحماية المؤقتة 2026 والفرق بينها وبين الإقامة', seo_description = 'الكملك هو بطاقة الحماية المؤقتة برقم يبدأ بـ99 وفق المادة 91 من قانون 6458، وحامله ليس مقيماً: أثر ذلك على التنقل بين الولايات وعبور الحدود والعودة.' WHERE slug = 'kimlik-temporary-protection-syria-2026';
UPDATE articles SET seo_title = 'قونيا 2026: 4 أحياء فقط مغلقة أمام تسجيل عناوين الأجانب', seo_description = 'الأحياء الأربعة المتبقّية: Sahibata في Meram، Şemsitebrizi في Karatay، İhsaniye وFerhuniye في Selçuklu. مقابل 18 حياً سابقاً، وكلّ ما عداها مفتوح للتسجيل.' WHERE slug = 'konya-closed-neighborhoods-list-2026';
UPDATE articles SET seo_title = 'سكن الطلاب الحكومي KYK للأجانب والسوريين 2026: الشروط', seo_description = 'الطالب الأجنبي يحق له التقديم على سكن KYK الحكومي، لكن برقم كملك ساري فقط دون استثناء. شروط الأهلية، الأوراق، التقديم عبر e-Devlet، والرسوم والمواعيد.' WHERE slug = 'kyk-yurt-devlet-yabanci-suriyeli-ogrenciler-2026';
UPDATE articles SET seo_title = 'تحويل رخصة القيادة إلى تركية 2026: الدول العربية المؤهّلة', seo_description = 'تونس والمغرب والجزائر تُحوَّل رخصها، وسوريا والعراق ومصر والأردن ولبنان لا. مهلة القيادة 6 أشهر، وبعدها غرامة تصل 30,000 ل.ت وسحب السيارة.' WHERE slug = 'license-conversion-arab-countries-2026';
UPDATE articles SET seo_title = 'تثبيت الزواج في البلدية التركية (Resmi Nikah)', seo_description = 'الزواج غير الرسمي لا يُعترف به قانونياً في تركيا ويسبب مشاكل في نسب الأطفال. إجراءات تثبيت الزواج في البلدية (Resmi Nikah) وحماية حقوق الأسرة.' WHERE slug = 'marriage-registration';
UPDATE articles SET seo_title = 'الماجستير والدكتوراه في تركيا 2026: الشروط والرسوم', seo_description = 'شروط قبول الأجانب في الدراسات العليا بتركيا: معدل 2.5/4.0 ومعادلة Denklik ولغة (IELTS 6.0 أو TÖMER C1)، وALES غير مطلوب غالباً، ورسوم من 500 ليرة' WHERE slug = 'masters-phd-turkey-foreigners-2026';
UPDATE articles SET seo_title = 'إجازة الأمومة في تركيا: 16 أسبوعاً و18 للحمل المتعدّد', seo_description = 'قانون العمل 4857 (المادة 74) يمنح 16 أسبوعاً: 8 قبل الولادة و8 بعدها، و18 للحمل المتعدّد. العمل حتى 3 أسابيع قبل الولادة، ساعة ونصف للرضاعة، وبدل SGK.' WHERE slug = 'maternity-leave-turkey-analik-izni';
UPDATE articles SET seo_title = 'MESEM للسوريين والأجانب 2026: مهنة براتب وتأمين SGK', seo_description = 'تتعلّم مهنة براتب وتأمين SGK بلا حدّ أعلى للعمر: من أنهى الصف الثامن ينال دبلوم الثانوية المهنية، وغيره شهادة الأستاذية، مع شرط اللغة A2 في بعض المراكز.' WHERE slug = 'mesem-vocational-training-syrians-foreigners-turkey-2026';
UPDATE articles SET seo_title = 'أخطاء MHRS وحلولها 2026: لماذا لا تستطيع حجز موعد', seo_description = 'حلول أخطاء MHRS: رسالة «لا يوجد تسجيل في النظام»، «لا يوجد تأمين فعّال»، وحظر 15 يوماً بعد الغياب عن موعد — وكيف تُفعّل Provizyon أو تحجز عبر خط 182.' WHERE slug = 'mhrs-errors-troubleshooting-2026';
UPDATE articles SET seo_title = 'حجز موعد طبي حكومي في تركيا 2026 عبر MHRS وخط ALO 182', seo_description = 'احجز في المستشفيات الحكومية وعيادات طب الأسرة عبر MHRS مجاناً: الدخول بكلمة مرور e-Devlet برقم يبدأ بـ99، أو بالاتصال بخط ALO 182 الذي يردّ بالعربية.' WHERE slug = 'mhrs-guide-syrians-arabs-2026';
UPDATE articles SET seo_title = 'نموذج الإعفاء من إذن العمل للكملك 2026: e-Devlet وSGK', seo_description = 'نموذج معلومات الإعفاء (Muafiyet Bilgi Formu) ليس إذن عمل بل يثبت أنك معفى منه: كيف تستخرجه من e-Devlet بعد ستة أشهر على الكملك، وواجبات صاحب العمل' WHERE slug = 'muafiyet-bilgi-formu-kimlik-work-permit-exemption-sgk-2026';
UPDATE articles SET seo_title = 'كيف تجد أقرب كاتب عدل (Noter) على الخريطة', seo_description = 'كثير من المعاملات القانونية في تركيا تحتاج تصديقاً لدى كاتب العدل (Noter). حدّد موقعك على خريطة النوتر لترى أقرب مكتب مع عنوانه وطريق الوصول إليه.' WHERE slug = 'nearest-notary-map';
UPDATE articles SET seo_title = 'تسجيل المولود في تركيا واستخراج شهادة الميلاد 2026', seo_description = 'يُسجَّل المولود في دائرة النفوس (Nüfus Müdürlüğü) بعد تقرير الولادة وضمن المهلة القانونية تفادياً للغرامة، وحاملو الحماية المؤقتة يسجّلون بالكملك.' WHERE slug = 'newborn-birth-registration-turkey';
UPDATE articles SET seo_title = 'تسجيل المولود الجديد واستخراج الكملك في تركيا', seo_description = 'تسجيل المولود الجديد في تركيا يجب أن يتم خلال 30 يوماً من الولادة للحصول على الكملك وتفادي الغرامات. خطوات التسجيل واستخراج هوية المولود.' WHERE slug = 'newborn-registration';
UPDATE articles SET seo_title = 'حجز موعد جواز سفر عبر بوابة المغتربين السورية', seo_description = 'كيفية استخدام بوابة المغتربين السورية لحجز موعد جواز السفر، مع أبرز المشاكل التقنية الشائعة أثناء الحجز وطريقة حلها، والرسوم الجديدة.' WHERE slug = 'passport-booking-system-legacy';
UPDATE articles SET seo_title = 'تتريك الهواتف (تقييد IMEI): الرسم والشروط عبر e-Devlet', seo_description = 'هاتفك الأجنبي يتوقف بعد 120 يوماً في تركيا؛ لإعادة تفعيله تدفع رسم (Harç) وتقيّده على جواز سفرك عبر e-Devlet، بشرط دخولك تركيا خلال آخر 365 يوماً.' WHERE slug = 'phone-imei-register';
UPDATE articles SET seo_title = 'المهن الممنوعة والمسموحة للأجانب في تركيا 2026 بالقوانين', seo_description = 'المهن المحصورة بالمواطنين الأتراك (29 بنداً) مع رقم القانون لكل مهنة: طب الأسنان 1219، الصيدلة 6197، المحاماة 1136 — ولماذا لا يغيّرها إعفاء السوريين.' WHERE slug = 'professions-foreigners-turkey-2026';
UPDATE articles SET seo_title = 'عقد الإيجار في تركيا 2026: سقف الزيادة وحقوق المستأجر', seo_description = 'سقف زيادة الإيجار عند التجديد في تموز 2026 هو 32.03% وفق متوسط 12 شهراً (المادة 344)، بعد انتهاء سقف الـ25% — وحقوق المستأجر وأسباب الإخلاء المحصورة.' WHERE slug = 'rent-contract-tenant-rights-turkey-2026';
UPDATE articles SET seo_title = 'رفض الإقامة في تركيا: الأسباب والاعتراض خلال 60 يوماً', seo_description = 'أسباب رفض الإقامة الأكثر تكراراً وفق المادة 33 من قانون 6458، وقاعدة الأيام العشرة للمغادرة، وكيف ترفع دعوى أمام المحكمة الإدارية خلال 60 يوماً من التبليغ.' WHERE slug = 'residence-rejection-appeal-turkey-2026';
UPDATE articles SET seo_title = 'نصائح القبول في المنحة التركية: رسالة الدافع والمقابلة', seo_description = 'من 200 ألف متقدّم يُقبل 4-5 آلاف فقط: هيكل رسالة الدافع وطولها 3,000-5,000 حرف، التحضير للمقابلة، وأخطاء ترفض ملفك فوراً كالنسخ واستخدام الذكاء الاصطناعي.' WHERE slug = 'scholarship-application-tips';
UPDATE articles SET seo_title = 'المنح الدراسية في تركيا 2026: مقارنة كل الخيارات للعرب', seo_description = 'مقارنة منح تركيا 2026: Türkiye Bursları التي تغطي الرسوم والسكن والراتب، إعفاء سابانجي 100%، راتب بيلكنت 1,500$ شهرياً، TÜBITAK 2215، YTB-IsDB، وErasmus+.' WHERE slug = 'scholarship-turkey-overview';
UPDATE articles SET seo_title = 'منح الجامعات التركية: سابانجي وبيلكنت وكوتش وTÜBITAK', seo_description = 'بدائل منحة الحكومة التركية التي لا يتجاوز قبولها 4%: سابانجي بإعفاء يصل 100% وسكن، بيلكنت براتب شهري حتى 1,500 دولار، كوتش، TÜBITAK 2215، ومنحة YTB-IsDB.' WHERE slug = 'scholarship-university-programs';
UPDATE articles SET seo_title = 'SGK 4A أم Bağ-Kur 4B للأجانب 2026: الفرق والأقساط', seo_description = 'الفرق بين 4A للموظفين بأجر و Bağ-Kur 4B للأعمال الحرة بأرقام 2026: خصم 14% من راتب الموظف مقابل قسط شهري يبدأ من 11,065 ليرة يدفعه صاحب العمل الحر بنفسه.' WHERE slug = 'sgk-4a-vs-bagkur-4b-foreigners-2026';
UPDATE articles SET seo_title = 'الدراسة في تركيا 2026: الجامعات والمنح والتكاليف', seo_description = 'المنحة التركية (راتب 3,500-7,000 ليرة وسكن وتأمين)، امتحان YÖS، رسوم الجامعات الحكومية والخاصة، معيشة 8,000-18,000 ليرة شهرياً، وإقامة الطالب' WHERE slug = 'study-in-turkey-universities-2026';
UPDATE articles SET seo_title = 'تجميد تسجيل السوريين في تركيا منذ 2022 والاستثناء الوحيد', seo_description = 'تركيا أوقفت تسجيل السوريين الجدد تحت الحماية المؤقتة منذ يونيو 2022 ولم تُلغِ القرار. الاستثناء الوحيد مواليد العائلات المسجّلة وفق المادة 21 وخطواته' WHERE slug = 'syria-registration-freeze-turkey';
UPDATE articles SET seo_title = 'معابر سوريا وتركيا 2026: الإقامة تعبر والكملك لا', seo_description = 'من 1 كانون الثاني 2026 يعبر حاملو بطاقة الإقامة أو إذن العمل برّاً عبر ستة معابر، وحامل الكملك غير مشمول حتى لو كان لديه إذن عمل. المعابر والشروط.' WHERE slug = 'syria-turkey-border-crossings-2026';
UPDATE articles SET seo_title = 'إعفاء السوريين من تصريح العمل: إعلان 26 حزيران 2026', seo_description = 'وزير الداخلية أعلن في 26 حزيران 2026 استبدال تصريح العمل بإعفاء (çalışma izni muafiyeti) للحماية المؤقتة. SGK يبقى إلزامياً، والنص التنفيذي لم يصدر' WHERE slug = 'syria-work-permit-exemption-turkey-2026-07';
UPDATE articles SET seo_title = 'القنصلية السورية في غازي عنتاب: العنوان وحجز الموعد 2026', seo_description = 'موقع القنصلية في حي غوفن ايفلر (شهيد كامل)، ولا رقم هاتف رسمي منشور: الحجز عبر تطبيق MOFA SY فقط ومجاناً. الدوام والخدمات والأوراق والرسوم.' WHERE slug = 'syrian-consulate-gaziantep-guide';
UPDATE articles SET seo_title = 'رسوم جواز السفر السوري 2026: 200 دولار عادي و400 مستعجل', seo_description = 'في القنصليات السورية: 200 دولار للدور العادي و400 للمستعجل، بشرط أن يكون الدولار إصدار 2017 أو أحدث. الأوراق المطلوبة وقواعد القاصرين والبصمة.' WHERE slug = 'syrian-passport-renewal';
UPDATE articles SET seo_title = 'أكواد التحديد (Tahdit) في تركيا: كيف تعرف وكيف تعترض', seo_description = 'كيف تتحقّق إن كان على ملفّك كود تحديد عبر إدارة الهجرة أو e-Devlet أو محامٍ، ولماذا لا تُنشر قائمة بمعاني الأكواد، وتصحيح خرافة مهلة الـ30 يوماً' WHERE slug = 'tahdit-entry-restriction-codes-how-to-object';
UPDATE articles SET seo_title = 'تعهّد الإخلاء في تركيا 2026: متى يُلزمك بالخروج ومتى يبطل', seo_description = 'المادة 352 من قانون الالتزامات 6098 تمنح المالك طريق إخلاء سريعاً خلال شهر: شروط صحّة تعهّد الإخلاء، متى يكون باطلاً، والفرق بينه وبين عقد الإيجار.' WHERE slug = 'tahliye-taahhutnamesi-eviction-undertaking-turkey-2026';
UPDATE articles SET seo_title = 'امتحان رخصة القيادة النظري بالعربية في تركيا 2026', seo_description = 'الامتحان النظري متاح بالعربية (Arapça): 50 سؤالاً في 45 دقيقة، والنجاح بـ35 إجابة صحيحة، والرسوم 950 ل.ت. توزيع المواضيع، التسجيل، وأسباب الرسوب الشائعة.' WHERE slug = 'theory-exam-arabic-2026';
UPDATE articles SET seo_title = 'سجل حوادث السيارة Tramer وكشف تلاعب العدّاد في تركيا', seo_description = 'قبل شراء سيارة مستعملة: سجل الأضرار Tramer/SBM يغطي تعويضات الحوادث منذ 2003، والاستعلام مجاني عبر e-Devlet للسيارة باسمك، مع كشف تلاعب الكيلومترات' WHERE slug = 'tramer-hasar-kaydi-kilometre-kontrol-turkiye-2026';
UPDATE articles SET seo_title = 'حجز تذاكر القطار السريع YHT عبر تطبيق TCDD', seo_description = 'حجز YHT يتم عبر قنوات TCDD الرسمية، والتذاكر تنفد سريعاً في المواسم فاحجز مبكراً. وأدخل بياناتك بدقة حتى لا تُرفض التذكرة عند الصعود.' WHERE slug = 'travel-tcdd-yht-app';
UPDATE articles SET seo_title = 'جدول تطعيمات الأطفال في تركيا 2026: المجاني والمدفوع', seo_description = 'لقاحات التقويم الوطني مجانية لكل طفل في مركز صحة العائلة دون شرط الجنسية أو التأمين. من الولادة حتى المدرسة، اللقاحات المدفوعة، والمتابعة عبر e-Nabız.' WHERE slug = 'turkey-child-vaccination-schedule-2026';
UPDATE articles SET seo_title = 'الفيزا العلاجية لتركيا: لماذا لا يصلح e-Visa وما البديل', seo_description = 'التأشيرة العلاجية تكون ملصقة من القنصلية لأن e-Visa مقصور على السياحة والتجارة. ما يقوّي الملف: تقرير طبي بالتشخيص، موعد المستشفى، ومدة إقامة مطابقة للخطة.' WHERE slug = 'turkey-medical-visa';
UPDATE articles SET seo_title = 'تأشيرة الدراسة التركية للسوريين 2026: 145$ + رسالة قبول YÖK', seo_description = 'رسم التأشيرة 145 دولاراً، ويلزم قبول جامعي برقم YÖK بصيغة XX-XXX-XX. الوثائق وحالات السوريين: تسجيل قديم، تخلٍّ عن الحماية المؤقتة، أو التقديم من بيروت.' WHERE slug = 'turkey-study-visa-syrians-2026';
UPDATE articles SET seo_title = 'تأشيرة النقل البري للسائقين السوريين 2026: سنوية، 165$', seo_description = 'التأشيرة الوحيدة السنوية متعدّدة الدخول للسوريين: رسمها 165 دولاراً، وتشترط جوازاً سارياً سنة كاملة وعقداً مع شركة نقل وسجلّاً جنائياً مترجماً محلَّفاً.' WHERE slug = 'turkey-truck-driver-visa-syrians-2026';
UPDATE articles SET seo_title = 'فيزا تركيا من لبنان 2026: السوري واللبناني والقناة الرسمية', seo_description = 'اللبناني معفى من التأشيرة حتى 90 يوماً خلال ستة أشهر للسياحة والعبور، أما السوري المقيم في لبنان فيحتاج تأشيرة ملصقة من القنصلية. الرابط وأسباب الرفض' WHERE slug = 'turkey-visa-from-lebanon';
UPDATE articles SET seo_title = 'سعر فيزا تركيا 2026 حسب الجنسية: الرسوم الرسمية ومَن هو معفى', seo_description = 'رسوم 2026 الرسمية: تأشيرة الدخول مرة واحدة 9,376.40 ليرة والمتعددة 31,410 ليرة، ومَن هو معفى (الأردن والسعودية ولبنان)، ولماذا لا إلكترونية للسوريين' WHERE slug = 'turkey-visa-types-2026';
UPDATE articles SET seo_title = 'إعفاء إذن الطريق للسوريين: مَن يستحقّه والثمن الصحّي', seo_description = 'الوثيقة صلاحيتها سنة وتغطّي كل الولايات، لكن الفئات المؤهَّلة غير معلَنة. واستخراج إذن عمل قد يُدخلك فجوة ثلاثين يوماً بلا خدمة صحية بحكم قانون 5510.' WHERE slug = 'turkey-yol-izni-muafiyeti-syrians-2026-06-09';
UPDATE articles SET seo_title = 'رفض الجنسية التركية 2026: الاعتراض ودعوى الإلغاء الإدارية', seo_description = 'الرفض بتقرير أمني قرار إداري قابل للطعن: مهلة 60 يوماً من تاريخ التبلّغ وفق القانون 2577، والفرق بين الاعتراض الإداري ودعوى الإلغاء وأيّهما يوقف المهلة.' WHERE slug = 'turkish-citizenship-rejection-appeal-annulment-lawsuit-2026';
UPDATE articles SET seo_title = 'مراحل الجنسية التركية 2026: معنى كل رسالة في ملف التجنيس', seo_description = '«المراحل السبع» وصف شعبي لا وجود له في القانون: المحطات الأربع الحقيقية لملف التجنيس، ومعنى كل رسالة في الاستعلام، ومتى يصبح التأخير سبباً للمراجعة.' WHERE slug = 'turkish-citizenship-stages-tracking-2026';
UPDATE articles SET seo_title = 'حجز موعد السفارة التركية في بيروت للم الشمل', seo_description = 'السفارة التركية في بيروت هي المنفذ الرئيسي للسوريين المقيمين في سوريا لإنجاز معاملات لم الشمل إلى تركيا. الإجراءات المطلوبة وخطوات حجز الموعد.' WHERE slug = 'turkish-embassy-beirut-family';
UPDATE articles SET seo_title = 'بدل البطالة في تركيا للأجانب: الشروط والمدة عبر İŞKUR', seo_description = 'لبدل البطالة تحتاج إقامة سارية و600 يوم أقساط خلال 3 سنوات وتقديماً لـİŞKUR خلال 30 يوماً من انتهاء العقد؛ والبدل 40% من متوسط الأجر لمدة 180 يوماً فأكثر.' WHERE slug = 'unemployment-benefit-iskur';
UPDATE articles SET seo_title = 'أحياء أورفا المغلقة 2026: القائمة الرسمية بـ26 حياً فقط', seo_description = 'قائمة مديرية الهجرة في شانلي أورفا: 26 حياً فقط بقي مغلقاً أمام تسجيل عناوين الأجانب في 6 أقضية، مقابل 170 حياً عام 2022، وسبعة أقضية باتت مفتوحة بالكامل.' WHERE slug = 'urfa-closed-neighborhoods-list-2026';
UPDATE articles SET seo_title = 'أحياء شانلي أورفا المغلقة 2026: 170 حياً بالقائمة الرسمية', seo_description = 'قائمة Göç İdaresi الرسمية بـ170 حياً مغلقاً أمام تسجيل الأجانب في شانلي أورفا على 13 قضاء: Akçakale 41 وKaraköprü 3 فقط — تحقق قبل توقيع عقد الإيجار.' WHERE slug = 'urfa-closed-neighborhoods-residence-2026';
UPDATE articles SET seo_title = 'الإقامة طويلة الأمد في تركيا 2026: شرط 8 سنوات والمزايا', seo_description = 'إقامة غير محدّدة المدة لمن أمضى 8 سنوات متواصلة بإقامة نظامية (المادة 42 من القانون 6458)، وسنوات الطالب تُحسب بنصفها: المزايا واستثناء الحماية المؤقتة.' WHERE slug = 'uzun-donem-ikamet-turkey-8-yil-2026';
UPDATE articles SET seo_title = 'الرقم الضريبي في تركيا للأجانب: استخراجه أونلاين مجاناً', seo_description = 'الرقم الضريبي (Vergi Numarası) عشرة أرقام تصدرها GİB مجاناً وفوراً عبر dijital.gib.gov.tr أو من مكتب الضرائب، ولا يترتّب عليه التزام ضريبي تلقائي.' WHERE slug = 'vergi-numarasi-tax-number-foreigners';
UPDATE articles SET seo_title = 'مواعيد العودة الطوعية إلى سوريا: randevu.goc.gov.tr 2026', seo_description = 'حجز موعد العودة الطوعية إلكترونياً عبر randevu.goc.gov.tr في 81 ولاية: خطوات الحجز برقم الكملك، المعابر البرية والجوية المعتمدة، وعمل الحدود 24 ساعة.' WHERE slug = 'voluntary-return-syria-appointment-system-2026';
UPDATE articles SET seo_title = 'العودة الطوعية إلى سوريا 2026: هل يمكنك الرجوع لتركيا؟', seo_description = 'لا حظر دخول على من يعود طوعاً، لكن الحماية المؤقتة تنتهي وتُسحب بطاقتك والعودة تصبح تأشيرة تقديرية بلا ضمان — والخطوات والفرق بين الزيارة والانتقال' WHERE slug = 'voluntary-return-syria-procedure-2026';
UPDATE articles SET seo_title = 'إصابة العمل (İş Kazası) للأجانب في تركيا 2026: حقوقك', seo_description = 'ما يُعدّ إصابة عمل بالمادة 13 من قانون 5510، والتبليغ إلى SGK خلال 3 أيام عمل، والعلاج مجاناً وتعويض راحة بثلثي راتبك، وتعويض العجز والورثة.' WHERE slug = 'work-injury-is-kazasi-foreigners-2026';
UPDATE articles SET seo_title = 'الإعفاء من إذن العمل في تركيا 2026: من لا يحتاج إذناً', seo_description = 'الفئات المعفاة من إذن العمل حسب القانون 6735 ومدة كل إعفاء: محاضرون شهر، رياضيون 3 أشهر، طلاب Erasmus 4 أشهر، عمل زراعي موسمي 6 أشهر، والرسم 13,539 ليرة.' WHERE slug = 'work-permit-exemption-2026';
UPDATE articles SET seo_title = 'فيزا العمل للسوريين العائدين إلى تركيا: المعايير والأوراق', seo_description = 'لا يوجد راتب ثابت: القاعدة الرسمية مضاعفات الحدّ الأدنى بحسب المهنة (مهندس 4×، مدير 3×). الأوراق المطلوبة منك ومن الشركة، والتقديم من قنصلية خارج تركيا.' WHERE slug = 'work-visa-syrians-return-turkey-2026-06';
UPDATE articles SET seo_title = 'حقوق العامل في تركيا 2026: الساعات والإجازات والفصل', seo_description = 'قانون العمل 4857: 45 ساعة أسبوعياً وسقف 11 ساعة يومياً، أجر العمل الإضافي +50% والمدد الزائدة +25%، والإجازات والفصل — وحقوقك حتى بلا عقد مكتوب.' WHERE slug = 'worker-rights-turkey-2026';
UPDATE articles SET seo_title = 'تثبيت الطلاق الأجنبي في تركيا 2026: Tanıma-Tenfiz والنفوس', seo_description = 'طريقان لتصحيح قيدك من «متزوّج» إلى «مطلّق»: التسجيل الإداري في النفوس (المادة 27/A) أو دعوى الاعتراف أمام محكمة الأسرة. الفرق بينهما والأوراق والمزالق.' WHERE slug = 'yabanci-bosanma-tanima-tenfiz-turkiye-2026';
UPDATE articles SET seo_title = 'YKS أم YÖS 2026؟ المعيار مكان الثانوية لا الجنسية', seo_description = 'ما يحدّد امتحانك هو مكان إنهاء الثانوية: داخلها YKS وخارجها YÖS. تغيير 2026 أخرج خرّيجي الثانويات التركية من حصص الخارج، واستثناءات مدارس السفارات وMOBIS.' WHERE slug = 'yks-vs-yos-placement-by-schooling-2026';
UPDATE articles SET seo_title = 'التأمين الإجباري للسيارة 2026: السعر الأعلى ودرجات الضرر', seo_description = 'هيئة SEDDK تضع السعر الأعلى (Tavan) وهو يتغيّر شهرياً، ونظام درجات الضرر من 0 إلى 8 يقرّر ما تدفعه فعلاً مع لوحة ولايتك وسجل حوادثك. وكيف تخفّضه.' WHERE slug = 'zorunlu-trafik-sigortasi-tavan-basamak-2026';

-- ═══════════════════════════════════════════════════════════════════════════
-- التحقّق
SELECT count(*) FILTER (WHERE length(seo_title) > 60)                       AS titles_still_too_long,
       count(*) FILTER (WHERE length(seo_description) > 160)                AS descs_still_too_long,
       count(*) FILTER (WHERE length(seo_description) BETWEEN 1 AND 69)     AS descs_still_too_short,
       count(*) FILTER (WHERE coalesce(seo_title,'') = '')                  AS titles_empty,
       count(*)                                                             AS total_published
FROM articles
WHERE status = 'approved' AND active IS NOT FALSE;
-- المتوقَّع بعد التشغيل: titles_still_too_long = 0، descs_still_too_long = 0.
-- ويبقى descs_still_too_short = 3 (المقالات الثلاثة المرفوضة عمداً)
-- و titles_empty = 32 (المقالات الكعوب — تحتاج محتوى أولاً، لا بيانات وصفية).
